# Generated by Django 5.2.4 on 2025-07-10 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_slug', models.CharField(db_index=True, max_length=100)),
                ('lote_id', models.IntegerField()),
                ('nombre_lote', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('auditado', models.BooleanField(default=False)),
                ('precio_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Lote global',
                'verbose_name_plural': 'Lotes globales',
                'unique_together': {('tenant_slug', 'lote_id')},
            },
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completado', 'Completado'), ('no_reparable', 'No reparable')], max_length=50)),
                ('coste', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparaciones', to='progeek.loteglobal')),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('precio_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notas', models.TextField(blank=True)),
                ('lote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valoracion', to='progeek.loteglobal')),
            ],
        ),
        migrations.CreateModel(
            name='DispositivoAuditado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo_id', models.IntegerField(blank=True, null=True)),
                ('tenant_slug', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado_fisico_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_funcional_cliente', models.CharField(blank=True, max_length=30, null=True)),
                ('estado_fisico_real', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_funcional_real', models.CharField(blank=True, max_length=30, null=True)),
                ('comentarios_auditor', models.TextField(blank=True, null=True)),
                ('imei_confirmado', models.BooleanField(blank=True, default=False, null=True)),
                ('precio_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_auditados', to='progeek.loteglobal')),
            ],
            options={
                'verbose_name': 'Dispositivo auditado',
                'verbose_name_plural': 'Dispositivos auditados',
                'unique_together': {('lote', 'dispositivo_id', 'tenant_slug')},
            },
        ),
    ]
