# Generated by Django 5.2.4 on 2025-07-16 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeek', '0003_userglobalrole_roles_por_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userglobalrole',
            name='roles_por_tenant',
        ),
        migrations.CreateModel(
            name='RolPorTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_slug', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('manager', 'Manager'), ('empleado', 'Empleado'), ('auditor', 'Auditor')], max_length=20)),
                ('tienda_id', models.IntegerField(blank=True, null=True)),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='progeek.userglobalrole')),
            ],
            options={
                'verbose_name': 'Rol por tenant',
                'verbose_name_plural': 'Roles por tenant',
                'unique_together': {('user_role', 'tenant_slug')},
            },
        ),
    ]
