# Generated by Django 5.2.4 on 2025-07-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeek', '0004_remove_userglobalrole_roles_por_tenant_rolportenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('recepcion_confirmada', 'Confirmación de recepción del lote'), ('oferta_enviada', 'Oferta enviada al cliente'), ('oferta_aceptada', 'Oferta aceptada'), ('recogida_generada', 'Recogida generada'), ('pago_realizado', 'Confirmación de pago'), ('recordatorio_pago', 'Recordatorio de pago pendiente')], max_length=50, unique=True)),
                ('asunto', models.CharField(max_length=255)),
                ('cuerpo', models.TextField(help_text='Puedes usar variables como {{ nombre_cliente }}, {{ nombre_oportunidad }}...')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
