# Generated by Django 5.2.4 on 2025-07-30 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeek', '0005_plantillacorreo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillacorreo',
            name='destinatario',
            field=models.CharField(default=django.utils.timezone.now, help_text='Puede contener variables como {{ cliente_email }} o emails fijos separados por comas.', max_length=255),
            preserve_default=False,
        ),
    ]
