# Generated by Django 5.2.4 on 2025-08-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeek', '0006_plantillacorreo_destinatario'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2CKycIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, unique=True)),
                ('tenant_slug', models.CharField(db_index=True, max_length=64)),
                ('contrato_id', models.BigIntegerField(db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'b2c_kyc_index',
            },
        ),
    ]
