# Generated by Django 5.2.4 on 2025-08-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeek', '0007_b2ckycindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicLegalVariables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.SlugField(default='default', unique=True)),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicLegalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('namespace', models.SlugField(default='default')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('version', models.CharField(default='v1', max_length=20)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['slug', 'namespace', 'is_active'], name='progeek_pub_slug_ba746b_idx')],
                'unique_together': {('slug', 'namespace', 'is_active')},
            },
        ),
    ]
