# Generated by Django 5.2.4 on 2025-10-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeek', '0008_publiclegalvariables_publiclegaltemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolportenant',
            name='managed_store_ids',
            field=models.JSONField(blank=True, default=list, help_text='IDs de tiendas gestionadas por Manager (regional o general). Lista vacía = todas las tiendas.'),
        ),
        migrations.AlterField(
            model_name='rolportenant',
            name='rol',
            field=models.CharField(choices=[('comercial', 'Comercial'), ('store_manager', 'Store Manager'), ('manager', 'Manager'), ('auditor', 'Auditor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rolportenant',
            name='tienda_id',
            field=models.IntegerField(blank=True, help_text='Tienda asignada para Comercial y Store Manager', null=True),
        ),
    ]
