# Generated by Django 5.2.4 on 2025-10-22 11:20

from django.db import migrations


def migrate_roles_forward(apps, schema_editor):
    """
    Migra roles del sistema antiguo al nuevo:
    - "empleado" → "comercial" (asume que empleados son comerciales)
    - "manager" → "store_manager" (managers de tienda específica)
    - "manager" sin tienda → "manager" (general manager, gestiona todas)
    - "auditor" → "auditor" (se mantiene igual)
    """
    RolPorTenant = apps.get_model('progeek', 'RolPorTenant')

    # Migrar empleados a comerciales
    empleados = RolPorTenant.objects.filter(rol='empleado')
    count_empleados = empleados.update(rol='comercial')
    print(f"✓ Migrados {count_empleados} empleados → comerciales")

    # Migrar managers con tienda asignada a store_managers
    managers_con_tienda = RolPorTenant.objects.filter(rol='manager', tienda_id__isnull=False)
    count_store_managers = managers_con_tienda.update(rol='store_manager')
    print(f"✓ Migrados {count_store_managers} managers con tienda → store_managers")

    # Los managers sin tienda específica se quedan como "manager" (general managers)
    managers_generales = RolPorTenant.objects.filter(rol='manager', tienda_id__isnull=True)
    count_general_managers = managers_generales.count()
    print(f"✓ {count_general_managers} managers generales mantenidos como 'manager'")

    # Auditors permanecen sin cambios
    auditores = RolPorTenant.objects.filter(rol='auditor')
    count_auditores = auditores.count()
    print(f"✓ {count_auditores} auditores mantenidos")


def migrate_roles_backward(apps, schema_editor):
    """
    Reversión: convierte roles nuevos a antiguos
    - "comercial" → "empleado"
    - "store_manager" → "manager"
    - "manager" → "manager"
    - "auditor" → "auditor"
    """
    RolPorTenant = apps.get_model('progeek', 'RolPorTenant')

    # Revertir comerciales a empleados
    RolPorTenant.objects.filter(rol='comercial').update(rol='empleado')

    # Revertir store_managers a managers
    RolPorTenant.objects.filter(rol='store_manager').update(rol='manager')

    # Managers y auditors ya están en formato antiguo
    print("✓ Roles revertidos al sistema antiguo")


class Migration(migrations.Migration):

    dependencies = [
        ('progeek', '0009_add_new_roles_and_managed_stores'),
    ]

    operations = [
        migrations.RunPython(migrate_roles_forward, migrate_roles_backward),
    ]
