# Generated by Django 5.2.4 on 2025-07-26 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.CharField(help_text='Schema donde se generó', max_length=100)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('estado_cambiado', 'Cambio de estado'), ('plazo_pago', 'Plazo de pago'), ('estado_prolongado', 'Estado prolongado'), ('otro', 'Otro')], max_length=30)),
                ('leida', models.BooleanField(default=False)),
                ('url_relacionada', models.CharField(blank=True, max_length=300)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creada'],
            },
        ),
    ]
