# Generated by Django 5.2.4 on 2025-10-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('estado_cambiado', 'Cambio de estado'), ('plazo_pago', 'Plazo de pago'), ('estado_prolongado', 'Estado prolongado'), ('chat', 'Mensaje de chat'), ('otro', 'Otro')], max_length=30),
        ),
    ]
