# Generated by Django 5.2.4 on 2025-10-03 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(help_text='IPv4 o IPv6', max_length=45, verbose_name='Dirección IP')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='País')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('was_blocked', models.BooleanField(default=False, help_text='Si el login fue bloqueado por razones de seguridad', verbose_name='Fue bloqueado')),
                ('block_reason', models.CharField(blank=True, choices=[('IMPOSSIBLE_TRAVEL', 'Viaje físicamente imposible'), ('DIFFERENT_COUNTRY', 'País diferente'), ('SUSPICIOUS_IP', 'IP sospechosa'), ('VPN_DETECTED', 'VPN detectada')], max_length=100, null=True, verbose_name='Razón de bloqueo')),
                ('alert_sent', models.BooleanField(default=False, help_text='Si se envió email de alerta al usuario', verbose_name='Alerta enviada')),
                ('user_agent', models.TextField(blank=True, help_text='Navegador y dispositivo usado', null=True, verbose_name='User Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Login',
                'verbose_name_plural': 'Historial de Logins',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='security_lo_user_id_011e6e_idx'), models.Index(fields=['ip'], name='security_lo_ip_ed07bc_idx'), models.Index(fields=['was_blocked'], name='security_lo_was_blo_4eab7e_idx')],
            },
        ),
    ]
