# Generated by Django 5.2.4 on 2025-10-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='region',
            field=models.CharField(blank=True, help_text='Provincia o estado (fallback cuando no hay ciudad)', max_length=100, null=True, verbose_name='Región/Provincia'),
        ),
    ]
