# Generated by Django 5.2.4 on 2025-07-10 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100)),
                ('pantalla', models.CharField(blank=True, max_length=50)),
                ('año', models.PositiveIntegerField(blank=True, null=True)),
                ('procesador', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['tipo', 'descripcion', 'año'],
                'unique_together': {('descripcion', 'tipo', 'pantalla', 'año', 'procesador')},
            },
        ),
        migrations.CreateModel(
            name='Capacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamaño', models.CharField(max_length=50)),
                ('precio_b2b', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('precio_b2c', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacidades', to='productos.modelo')),
            ],
            options={
                'ordering': ['modelo', 'tamaño'],
                'unique_together': {('modelo', 'tamaño')},
            },
        ),
    ]
