# Generated by Django 5.2.4 on 2025-08-31 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManoObraTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32, unique=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=128)),
                ('coste_por_minuto', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PiezaTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, unique=True)),
                ('categoria', models.CharField(blank=True, default='', max_length=64)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CostoPieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coste_neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('minutos', models.PositiveIntegerField(default=0)),
                ('mano_obra_fija_neta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('proveedor', models.CharField(blank=True, default='', max_length=64)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('capacidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costes_piezas', to='productos.capacidad')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costes_piezas', to='productos.modelo')),
                ('mano_obra_tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.manoobratipo')),
                ('pieza_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costes', to='productos.piezatipo')),
            ],
            options={
                'indexes': [models.Index(fields=['modelo', 'pieza_tipo', 'valid_from'], name='productos_c_modelo__bb04db_idx'), models.Index(fields=['valid_to'], name='productos_c_valid_t_16bcdf_idx')],
            },
        ),
        migrations.CreateModel(
            name='PrecioRecompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('B2B', 'B2B (recompra)'), ('B2C', 'B2C (recompra)')], max_length=3)),
                ('fuente', models.CharField(default='manual', max_length=50)),
                ('moneda', models.CharField(default='EUR', max_length=3)),
                ('precio_neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('tenant_schema', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capacidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_recompra', to='productos.capacidad')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['capacidad', 'canal', 'valid_from'], name='productos_p_capacid_448a9c_idx'), models.Index(fields=['valid_to'], name='productos_p_valid_t_f4af9a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True)), fields=('capacidad', 'canal', 'fuente', 'tenant_schema'), name='uniq_precio_recompra_vigente_por_clave')],
            },
        ),
    ]
