# Generated by Django 5.2.4 on 2025-08-31 11:48

from django.db import migrations

from django.db import migrations
from django.utils import timezone


def copiar_precios(apps, schema_editor):
    PrecioRecompra = apps.get_model('productos', 'PrecioRecompra')
    ProductoCapacidad = apps.get_model('productos', 'Capacidad')

    now = timezone.now()

    for cap in ProductoCapacidad.objects.all():
        # Si existen, crea filas B2B y B2C como 'manual'
        b2b = getattr(cap, 'precio_b2b', None)
        b2c = getattr(cap, 'precio_b2c', None)

        if b2b is not None:
            PrecioRecompra.objects.create(
                capacidad_id=cap.id,
                canal='B2B',
                fuente='manual',
                moneda='EUR',
                precio_neto=b2b,
                valid_from=now,
                valid_to=None,
                tenant_schema=None,
            )
        if b2c is not None:
            PrecioRecompra.objects.create(
                capacidad_id=cap.id,
                canal='B2C',
                fuente='manual',
                moneda='EUR',
                precio_neto=b2c,
                valid_from=now,
                valid_to=None,
                tenant_schema=None,
            )


def revertir(apps, schema_editor):
    PrecioRecompra = apps.get_model('productos', 'PrecioRecompra')
    # Solo borra los que vengan de la migración manual en este instante (heurística)
    PrecioRecompra.objects.filter(fuente='manual').delete()



class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_manoobratipo_piezatipo_costopieza_preciorecompra'),
    ]

    operations = [
    ]
