# Generated by Django 5.2.4 on 2025-08-31 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_migrar_precios_desde_capacidad'),
        ('productos', '0004_backfill_precio_recompra'),
    ]

    operations = [
    ]
