# Generated by Django 5.2.4 on 2025-09-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_merge_20250831_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manoobratipo',
            old_name='coste_por_minuto',
            new_name='coste_por_hora',
        ),
        migrations.RemoveField(
            model_name='costopieza',
            name='minutos',
        ),
        migrations.AddField(
            model_name='costopieza',
            name='horas',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
