# Generated by Django 5.2.4 on 2025-09-01 12:04

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_rename_coste_por_minuto_manoobratipo_coste_por_hora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaActualizacionLikewize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('SUCCESS', 'SUCCESS'), ('ERROR', 'ERROR')], default='PENDING', max_length=16)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('iniciado_en', models.DateTimeField(blank=True, null=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('total_modelos', models.IntegerField(blank=True, null=True)),
                ('csv_path', models.CharField(blank=True, default='', max_length=512)),
                ('csv_corregido_path', models.CharField(blank=True, default='', max_length=512)),
                ('log_path', models.CharField(blank=True, default='', max_length=512)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'precios_tarea_actualizacion_likewize',
            },
        ),
    ]
