# Generated by Django 5.2.4 on 2025-09-01 12:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_tareaactualizacionlikewize'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikewizeItemStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('modelo_norm', models.CharField(max_length=255)),
                ('almacenamiento_gb', models.IntegerField(null=True)),
                ('precio_b2b', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staging', to='productos.tareaactualizacionlikewize')),
            ],
            options={
                'db_table': 'precios_likewize_staging',
                'indexes': [models.Index(fields=['tarea', 'tipo', 'modelo_norm', 'almacenamiento_gb'], name='precios_lik_tarea_i_08f388_idx')],
                'unique_together': {('tarea', 'tipo', 'modelo_norm', 'almacenamiento_gb')},
            },
        ),
    ]
