# Generated by Django 5.2.4 on 2025-09-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_likewizeitemstaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareaactualizacionlikewize',
            name='progreso',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tareaactualizacionlikewize',
            name='subestado',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
