# Generated by Django 5.2.4 on 2025-09-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_tareaactualizacionlikewize_progreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='likewizeitemstaging',
            name='capacidad_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='likewizeitemstaging',
            index=models.Index(fields=['tarea', 'capacidad_id'], name='precios_lik_tarea_i_ce68ec_idx'),
        ),
    ]
