# Generated by Django 5.2.4 on 2025-09-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_likewizeitemstaging_capacidad_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='likewizeitemstaging',
            name='a_number',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='likewizeitemstaging',
            name='any',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='likewizeitemstaging',
            name='cpu',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='likewizeitemstaging',
            name='disco',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='likewizeitemstaging',
            name='modelo_raw',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='likewizeitemstaging',
            name='pulgadas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='likewizeitemstaging',
            index=models.Index(fields=['tarea', 'a_number'], name='precios_lik_tarea_i_f8c8e9_idx'),
        ),
    ]
