# Generated by Django 5.2.4 on 2025-09-03 08:48

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_likewizeitemstaging_a_number_likewizeitemstaging_any_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikewizeCazadorTarea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_likewize', models.PositiveIntegerField(default=0)),
                ('matches', models.JSONField(blank=True, default=list)),
                ('no_cazados_bd', models.JSONField(blank=True, default=list)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarea de Cazado Likewize',
                'verbose_name_plural': 'Tareas de Cazado Likewize',
                'db_table': 'progeek_likewize_cazador_tarea',
            },
        ),
    ]
