# Generated by Django on 2025-09-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_likewizecazadortarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='likewizecazadortarea',
            name='no_cazados_likewize',
            field=models.JSONField(blank=True, default=list),
        ),
    ]

