# Generated by Django 5.2.4 on 2025-09-07 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_likewizecazadortarea_no_cazados_likewize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacidad',
            name='precio_b2b',
        ),
        migrations.RemoveField(
            model_name='capacidad',
            name='precio_b2c',
        ),
    ]
