# Generated by Django 5.2.4 on 2025-09-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_capacidad_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelo',
            options={'ordering': ['marca', 'tipo', 'descripcion', 'año']},
        ),
        migrations.AlterUniqueTogether(
            name='modelo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='modelo',
            name='marca',
            field=models.CharField(default='Apple', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='modelo',
            unique_together={('descripcion', 'tipo', 'marca', 'pantalla', 'año', 'procesador')},
        ),
    ]
