# Generated by Django 5.2.4 on 2025-09-28 09:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0019_modelo_likewize_modelo_likewizeitemstaging_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(default='likewize', max_length=32)),
                ('source_brand', models.CharField(db_index=True, max_length=100)),
                ('source_type', models.CharField(db_index=True, max_length=50)),
                ('source_model_raw', models.CharField(max_length=512)),
                ('source_model_normalized', models.CharField(db_index=True, max_length=255)),
                ('source_capacity_gb', models.IntegerField(blank=True, db_index=True, null=True)),
                ('a_number', models.CharField(blank=True, db_index=True, default='', max_length=8)),
                ('screen_size', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('cpu', models.CharField(blank=True, default='', max_length=128)),
                ('gpu_cores', models.IntegerField(blank=True, null=True)),
                ('likewize_model_code', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('likewize_master_model_id', models.CharField(blank=True, default='', max_length=50)),
                ('mapped_capacity_id', models.IntegerField(db_index=True)),
                ('mapped_model_description', models.CharField(max_length=255)),
                ('mapped_capacity_size', models.CharField(max_length=50)),
                ('confidence_score', models.IntegerField(default=0)),
                ('mapping_algorithm', models.CharField(default='fuzzy', max_length=50)),
                ('first_mapped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_confirmed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('times_confirmed', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('needs_review', models.BooleanField(db_index=True, default=False)),
                ('review_reason', models.CharField(blank=True, default='', max_length=200)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('invalidation_reason', models.CharField(blank=True, default='', max_length=200)),
                ('mapping_version', models.CharField(default='1.0', max_length=20)),
            ],
            options={
                'db_table': 'productos_device_mapping',
                'ordering': ['-last_confirmed_at'],
                'indexes': [models.Index(fields=['source', 'source_brand', 'source_type', 'source_model_normalized'], name='productos_d_source_d138ee_idx'), models.Index(fields=['source', 'source_brand', 'source_capacity_gb'], name='productos_d_source_ddca81_idx'), models.Index(fields=['a_number', 'screen_size', 'year'], name='productos_d_a_numbe_2a9041_idx'), models.Index(fields=['likewize_model_code', 'source_brand'], name='productos_d_likewiz_a80eb9_idx'), models.Index(fields=['is_active', 'confidence_score'], name='productos_d_is_acti_aed584_idx'), models.Index(fields=['needs_review', 'last_confirmed_at'], name='productos_d_needs_r_ac9d84_idx'), models.Index(fields=['first_mapped_at', 'source_brand'], name='productos_d_first_m_e32854_idx')],
                'unique_together': {('source', 'source_brand', 'source_model_normalized', 'source_capacity_gb', 'a_number')},
            },
        ),
        migrations.CreateModel(
            name='MappingMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('source', models.CharField(default='likewize', max_length=32)),
                ('brand', models.CharField(db_index=True, max_length=100)),
                ('device_type', models.CharField(db_index=True, max_length=50)),
                ('total_processed', models.PositiveIntegerField(default=0)),
                ('successfully_mapped', models.PositiveIntegerField(default=0)),
                ('cached_mappings_used', models.PositiveIntegerField(default=0)),
                ('new_mappings_created', models.PositiveIntegerField(default=0)),
                ('avg_confidence_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('mappings_needing_review', models.PositiveIntegerField(default=0)),
                ('avg_processing_time', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'productos_mapping_metrics',
                'ordering': ['-date', 'brand', 'device_type'],
                'indexes': [models.Index(fields=['date', 'source'], name='productos_m_date_6a78d3_idx'), models.Index(fields=['brand', 'device_type', 'date'], name='productos_m_brand_55b018_idx')],
                'unique_together': {('date', 'source', 'brand', 'device_type')},
            },
        ),
        migrations.CreateModel(
            name='MappingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('correct', 'Correcto'), ('incorrect', 'Incorrecto'), ('needs_review', 'Necesita revisión'), ('alternative', 'Alternativa sugerida')], max_length=20)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, default='', max_length=100)),
                ('comments', models.TextField(blank=True, default='')),
                ('suggested_capacity_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='productos.devicemapping')),
            ],
            options={
                'db_table': 'productos_mapping_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mapping', 'feedback_type'], name='productos_m_mapping_a6ba0b_idx'), models.Index(fields=['processed', 'created_at'], name='productos_m_process_205c67_idx')],
            },
        ),
    ]
