# Generated by Django 5.2.4 on 2025-10-01 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0022_add_autoaprendizaje_v3'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dispositivo', models.CharField(help_text='Tipo de dispositivo (iPhone, iPad, MacBook Air, MacBook Pro, iMac, etc.)', max_length=100, unique=True)),
                ('pp_A', models.DecimalField(decimal_places=4, default=0.08, help_text='Penalización de A+ a A (0.08 = 8%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('pp_B', models.DecimalField(decimal_places=4, default=0.12, help_text='Penalización de A a B (0.12 = 12%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('pp_C', models.DecimalField(decimal_places=4, default=0.15, help_text='Penalización de B a C (0.15 = 15%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('pp_funcional', models.DecimalField(decimal_places=4, default=0.15, help_text='Penalización funcional (0.15 = 15%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('battery_health_threshold', models.IntegerField(blank=True, default=85, help_text='Umbral de salud de batería para aplicar deducción (85%)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('has_battery', models.BooleanField(default=True, help_text='¿El dispositivo tiene batería? (True para iPhone, iPad, MacBook; False para iMac, Mac Pro, etc.)')),
                ('has_display', models.BooleanField(default=True, help_text='¿El dispositivo tiene pantalla integrada? (True para iPhone, iPad, MacBook, iMac; False para Mac Pro, Mac Studio, Mac mini)')),
                ('activo', models.BooleanField(default=True, help_text='¿Esta configuración está activa?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Grading',
                'verbose_name_plural': 'Configuraciones de Grading',
                'db_table': 'productos_grading_config',
                'ordering': ['tipo_dispositivo'],
            },
        ),
        migrations.RenameIndex(
            model_name='featurepattern',
            new_name='productos_f_pattern_0aadd3_idx',
            old_name='productos_f_pattern_5d7e2a_idx',
        ),
        migrations.RenameIndex(
            model_name='featurepattern',
            new_name='productos_f_confide_b52269_idx',
            old_name='productos_f_confide_8f9c3b_idx',
        ),
        migrations.RenameIndex(
            model_name='learningsession',
            new_name='productos_l_tarea_i_3f200b_idx',
            old_name='productos_l_tarea_i_4a7f8d_idx',
        ),
        migrations.RenameIndex(
            model_name='learningsession',
            new_name='productos_l_predict_cf0fd6_idx',
            old_name='productos_l_predict_9e8a7c_idx',
        ),
        migrations.RenameIndex(
            model_name='likewizeknowledgebase',
            new_name='productos_l_likewiz_3610c5_idx',
            old_name='productos_l_likewiz_98eb42_idx',
        ),
        migrations.RenameIndex(
            model_name='likewizeknowledgebase',
            new_name='productos_l_last_us_408586_idx',
            old_name='productos_l_last_us_21c8f4_idx',
        ),
        migrations.RenameIndex(
            model_name='likewizeknowledgebase',
            new_name='productos_l_user_va_66f25c_idx',
            old_name='productos_l_user_va_9c4a1b_idx',
        ),
        migrations.RenameIndex(
            model_name='likewizeknowledgebase',
            new_name='productos_l_success_6fdf44_idx',
            old_name='productos_l_success_8a2e1f_idx',
        ),
        migrations.RenameIndex(
            model_name='mappingcorrection',
            new_name='productos_m_created_5d3f05_idx',
            old_name='productos_m_created_3c4b8f_idx',
        ),
        migrations.RenameIndex(
            model_name='mappingcorrection',
            new_name='productos_m_correct_456cf0_idx',
            old_name='productos_m_correct_7a8d9e_idx',
        ),
        migrations.RemoveField(
            model_name='likewizeitemstaging',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='likewizeitemstaging',
            name='phone_model_id',
        ),
    ]
