# Generated by Django 5.2.4 on 2025-10-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0026_fix_precio_recompra_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemappingv2',
            name='mapping_algorithm',
            field=models.CharField(choices=[('a_number_direct', 'Mapeo directo por A-number'), ('exact_name_match', 'Coincidencia exacta de nombre'), ('tech_specs_match', 'Coincidencia por especificaciones'), ('fuzzy_similarity', 'Similitud difusa'), ('ml_prediction', 'Predicción por ML'), ('heuristic_rules', 'Reglas heurísticas'), ('manual_override', 'Mapeo manual'), ('v4_generation', 'v4 - Matching por generación'), ('v4_a_number', 'v4 - Matching por A-number'), ('v4_exact', 'v4 - Matching exacto'), ('v4_fuzzy', 'v4 - Matching difuso'), ('v4', 'v4 - Motor TDD')], max_length=50),
        ),
    ]
