# Generated by Django 5.2.4 on 2025-10-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0027_alter_devicemappingv2_mapping_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='likewizeitemstaging',
            name='mapping_metadata',
            field=models.JSONField(blank=True, default=None, help_text='Metadatos del sistema de mapeo: confidence_score, mapping_algorithm, needs_review, is_mapped', null=True),
        ),
    ]
