# Generated by Django 5.2.4 on 2025-10-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0028_add_mapping_metadata_to_staging'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(help_text='Fabricante del dispositivo (ej: Samsung, HP, Dell)', max_length=100)),
                ('modelo', models.CharField(help_text='Modelo específico del dispositivo', max_length=255)),
                ('tipo', models.CharField(choices=[('movil', 'Móvil'), ('portatil', 'Portátil'), ('tablet', 'Tablet'), ('monitor', 'Monitor'), ('otro', 'Otro')], default='movil', help_text='Tipo de dispositivo', max_length=20)),
                ('capacidad', models.CharField(help_text='Capacidad de almacenamiento (ej: 256GB, 512GB, 1TB SSD)', max_length=100)),
                ('precio_base_b2b', models.DecimalField(decimal_places=2, help_text='Precio de compra para clientes B2B (empresas/autónomos) en euros', max_digits=10)),
                ('precio_base_b2c', models.DecimalField(decimal_places=2, help_text='Precio de venta para clientes B2C (particulares) en euros', max_digits=10)),
                ('ajuste_excelente', models.DecimalField(decimal_places=2, default=100.0, help_text='Porcentaje del precio base para estado excelente (recomendado: 100%)', max_digits=5)),
                ('ajuste_bueno', models.DecimalField(decimal_places=2, default=80.0, help_text='Porcentaje del precio base para estado bueno (recomendado: 70-85%)', max_digits=5)),
                ('ajuste_malo', models.DecimalField(decimal_places=2, default=50.0, help_text='Porcentaje del precio base para estado malo (recomendado: 40-60%)', max_digits=5)),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, aparecerá en el formulario de valoración')),
                ('descripcion_completa', models.CharField(editable=False, help_text='Descripción auto-generada: Marca Modelo Capacidad', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dispositivo Personalizado',
                'verbose_name_plural': 'Dispositivos Personalizados',
                'db_table': 'dispositivos_personalizados',
                'ordering': ['marca', 'tipo', 'modelo', 'capacidad'],
                'unique_together': {('marca', 'modelo', 'capacidad')},
            },
        ),
    ]
