# Generated by Django 5.2.4 on 2025-10-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0030_add_campos_faltantes_dispositivo_personalizado'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dispositivopersonalizado',
            new_name='dispositivo_marca_f05dcf_idx',
            old_name='dispositivo_marca_m_idx',
        ),
        migrations.RenameIndex(
            model_name='dispositivopersonalizado',
            new_name='dispositivo_tipo_a27dd1_idx',
            old_name='dispositivo_tipo_idx',
        ),
        migrations.RenameIndex(
            model_name='dispositivopersonalizado',
            new_name='dispositivo_activo_97330f_idx',
            old_name='dispositivo_activo_idx',
        ),
        migrations.AlterField(
            model_name='dispositivopersonalizado',
            name='activo',
            field=models.BooleanField(default=True, help_text='Soft delete: False para desactivar'),
        ),
        migrations.AlterField(
            model_name='dispositivopersonalizado',
            name='descripcion_completa',
            field=models.CharField(blank=True, default='', help_text='Descripción auto-generada: Marca Modelo Capacidad', max_length=500),
        ),
        migrations.AlterField(
            model_name='dispositivopersonalizado',
            name='marca',
            field=models.CharField(help_text='Marca del dispositivo (Samsung, Xiaomi, Dell, LG, etc.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='dispositivopersonalizado',
            name='notas',
            field=models.TextField(blank=True, help_text='Descripción adicional o detalles específicos'),
        ),
        migrations.AlterField(
            model_name='dispositivopersonalizado',
            name='precio_base_b2b',
            field=models.DecimalField(decimal_places=2, help_text='Precio base para canal B2B', max_digits=10),
        ),
        migrations.AlterField(
            model_name='dispositivopersonalizado',
            name='precio_base_b2c',
            field=models.DecimalField(decimal_places=2, help_text='Precio base para canal B2C', max_digits=10),
        ),
    ]
