# Generated by Django 5.2.4 on 2025-10-20 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0031_rename_dispositivo_marca_m_idx_dispositivo_marca_f05dcf_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivopersonalizado',
            name='ajuste_bueno',
        ),
        migrations.RemoveField(
            model_name='dispositivopersonalizado',
            name='ajuste_excelente',
        ),
        migrations.RemoveField(
            model_name='dispositivopersonalizado',
            name='ajuste_malo',
        ),
        migrations.RemoveField(
            model_name='dispositivopersonalizado',
            name='precio_base_b2b',
        ),
        migrations.RemoveField(
            model_name='dispositivopersonalizado',
            name='precio_base_b2c',
        ),
        migrations.AlterField(
            model_name='dispositivopersonalizado',
            name='tipo',
            field=models.CharField(choices=[('movil', 'Móvil'), ('portatil', 'Portátil'), ('pc', 'PC (Desktop/Torre)'), ('monitor', 'Monitor'), ('tablet', 'Tablet'), ('otro', 'Otro')], default='otro', help_text='Tipo de dispositivo', max_length=20),
        ),
        migrations.CreateModel(
            name='PrecioDispositivoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('B2B', 'B2B (recompra)'), ('B2C', 'B2C (recompra)')], help_text='Canal de venta (B2B o B2C)', max_length=3)),
                ('fuente', models.CharField(default='manual', help_text='Origen del precio: manual, api, importación', max_length=50)),
                ('moneda', models.CharField(default='EUR', max_length=3)),
                ('precio_neto', models.DecimalField(decimal_places=2, help_text='Precio sin IVA', max_digits=12)),
                ('valid_from', models.DateTimeField(help_text='Fecha/hora desde la cual este precio es válido')),
                ('valid_to', models.DateTimeField(blank=True, help_text='Fecha/hora hasta la cual este precio es válido. NULL = vigente indefinidamente', null=True)),
                ('tenant_schema', models.CharField(blank=True, help_text='Schema del tenant (para overrides específicos por tenant)', max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='Usuario que creó/modificó este precio', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dispositivo_personalizado', models.ForeignKey(help_text='Dispositivo personalizado al que pertenece este precio', on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='productos.dispositivopersonalizado')),
            ],
            options={
                'verbose_name': 'Precio Dispositivo Personalizado',
                'verbose_name_plural': 'Precios Dispositivos Personalizados',
                'db_table': 'precios_dispositivos_personalizados',
                'ordering': ['-valid_from'],
                'indexes': [models.Index(fields=['dispositivo_personalizado', 'canal', 'valid_from'], name='precios_dis_disposi_9c8e84_idx'), models.Index(fields=['valid_to'], name='precios_dis_valid_t_59f923_idx'), models.Index(fields=['tenant_schema'], name='precios_dis_tenant__84ffe1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True)), fields=('dispositivo_personalizado', 'canal', 'tenant_schema'), name='uniq_precio_dispositivo_personalizado_vigente')],
            },
        ),
    ]
