# Generated by Django 5.2.4 on 2025-10-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0032_remove_dispositivopersonalizado_ajuste_bueno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivopersonalizado',
            name='pp_A',
            field=models.DecimalField(decimal_places=4, default=0.08, help_text='Penalización de A+ a A (0.08 = 8%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='dispositivopersonalizado',
            name='pp_B',
            field=models.DecimalField(decimal_places=4, default=0.12, help_text='Penalización de A a B (0.12 = 12%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='dispositivopersonalizado',
            name='pp_C',
            field=models.DecimalField(decimal_places=4, default=0.15, help_text='Penalización de B a C (0.15 = 15%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='dispositivopersonalizado',
            name='precio_suelo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio mínimo ofertable (V_SUELO)', max_digits=10),
        ),
    ]
