# Generated by Django 5.2.4 on 2025-07-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_contacto_comercial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='goal',
            field=models.TextField(blank=True),
        ),
    ]
