# Generated by Django 5.2.4 on 2025-07-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='correo_comercial',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='correo_financiero',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
