# Generated by Django 5.2.4 on 2025-07-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_correo_comercial_company_correo_financiero'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cif',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
