# Generated by Django 5.2.4 on 2025-07-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_cif'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tier',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
