# Generated by Django 5.2.4 on 2025-08-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_company_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='tipo_cliente',
        ),
        migrations.AddField(
            model_name='company',
            name='legal_namespace',
            field=models.SlugField(default='default', help_text='Conjunto público de condiciones (default, autoadmin, brand-x, ...)'),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Overrides JSON. Ej.: {"empresa": {"nombre": "...", "email": "..."}}'),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_slug',
            field=models.SlugField(default='b2c-condiciones', help_text='Slug de la plantilla legal a usar (p.ej. b2c-condiciones, b2b-condiciones)'),
        ),
        migrations.AddField(
            model_name='company',
            name='management_mode',
            field=models.CharField(choices=[('default', 'Gestionado por Progeek y plantillas globales'), ('autoadmin', 'Autoadministrado y plantillas propias')], default='default', max_length=12),
        ),
    ]
