# Generated by Django 5.2.4 on 2025-08-15 15:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_remove_company_tipo_cliente_company_legal_namespace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='comision_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Porcentaje de comisión aplicado al partner (0–100).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
