# Generated by Codex on 2025-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_company_comision_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='solo_empresas',
            field=models.BooleanField(default=False, help_text='Si está activo, el partner solo opera con clientes empresa/autónomos.'),
        ),
    ]

