# Generated by Codex on 2025-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_company_solo_empresas'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='acuerdo_empresas',
            field=models.TextField(blank=True, help_text='Detalle del acuerdo vigente entre las empresas.'),
        ),
    ]
