# Generated by Codex on 2025-02-14

from django.db import migrations, models
import django_test_app.companies.models
import checkouters.storage


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_company_acuerdo_empresas'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='acuerdo_empresas_pdf',
            field=models.FileField(blank=True, help_text='Archivo PDF del acuerdo firmado entre las empresas.', null=True, storage=checkouters.storage.PrivateDocumentStorage(), upload_to=django_test_app.companies.models.agreement_upload_path),
        ),
    ]
