# Generated by Django 5.2.4 on 2025-09-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_company_acuerdo_empresas_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='es_demo',
            field=models.BooleanField(default=False, help_text='Modo demo: permite usar cualquier correo, DNI, CIF, etc. sin validación estricta.'),
        ),
    ]
