# Generated by Django 5.2.4 on 2025-10-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_update_logo_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('pendiente', 'Pendiente')], default='activo', help_text='Estado operativo del partner.', max_length=20),
        ),
    ]
