import {
  Pending,
  CheckCircle,
  Cancel,
  LocalShipping,
  Inventory2,
  ReceiptLong,
  Description,
  Undo,
  Send,
  AssignmentTurnedIn,
  EditNote,
  GppMaybe,
  RuleFolder,
  Article,
} from '@mui/icons-material'
import EuroIcon from '@mui/icons-material/Euro';
import type { ChipProps } from '@mui/material/Chip';
type ChipColor = NonNullable<ChipProps['color']>;

export const ESTADOS_META: Record<string, { color: ChipColor; icon?: React.ElementType }> = {
  "Pendiente": { color: "warning", icon: Pending },
  "Aceptado": { color: "success", icon: CheckCircle },
  "Cancelado": { color: "error", icon: Cancel },
  "Recogida solicitada": { color: "info", icon: LocalShipping },
  "Recogida generada": { color: "info", icon: LocalShipping },
  "En tránsito": { color: "info", icon: LocalShipping },
  "Recibido": { color: "success", icon: Inventory2 },
  "Check in OK":{ color: "info", icon: LocalShipping },
  "En revisión": { color: "secondary", icon: EditNote },
  "Oferta confirmada": { color: "success", icon: CheckCircle },
  "Pendiente factura": { color: "warning", icon: ReceiptLong },
  "Factura recibida": { color: "info", icon: Description },
  "Pendiente de pago": { color: "warning", icon: ReceiptLong },
  "Pagado": { color: "success", icon: EuroIcon },

  "Nueva oferta": { color: "primary", icon: Send },
  "Nueva oferta enviada": { color: "primary", icon: Send },
  "Nueva oferta confirmada": { color: "success", icon: CheckCircle },
  "Rechazada": { color: "error", icon: GppMaybe },
  "Devolución iniciada": { color: "warning", icon: Undo },
  "Equipo enviado": { color: "info", icon: LocalShipping },
  "Recibido por el cliente": { color: "success", icon: AssignmentTurnedIn },
  "Nuevo contrato": { color: "primary", icon: Article },
  "Contrato firmado": { color: "primary", icon: RuleFolder },
}
export const ESTADOS_B2B: Record<string, { color: ChipColor; icon?: React.ElementType }> = {
  "Pendiente": { color: "warning", icon: Pending },
  "Aceptado": { color: "success", icon: CheckCircle },
  "Cancelado": { color: "error", icon: Cancel },
  "Recogida solicitada": { color: "info", icon: LocalShipping },
  "Recogida generada": { color: "info", icon: LocalShipping },
  "En tránsito": { color: "info", icon: LocalShipping },
  "Check in OK":{ color: "info", icon: LocalShipping },
  "Recibido": { color: "success", icon: Inventory2 },
  "En revisión": { color: "secondary", icon: EditNote },
  "Oferta confirmada": { color: "success", icon: CheckCircle },
  "Pendiente factura": { color: "warning", icon: ReceiptLong },
  "Factura recibida": { color: "info", icon: Description },
  "Pendiente de pago": { color: "warning", icon: ReceiptLong },
  "Pagado": { color: "success", icon: EuroIcon },

  "Nueva oferta": { color: "primary", icon: Send },
  "Nueva oferta enviada": { color: "primary", icon: Send },
  "Nueva oferta confirmada": { color: "success", icon: CheckCircle },
  "Rechazada": { color: "error", icon: GppMaybe },
  "Devolución iniciada": { color: "warning", icon: Undo },
  "Equipo enviado": { color: "info", icon: LocalShipping },
  "Recibido por el cliente": { color: "success", icon: AssignmentTurnedIn },
}

export const ESTADO_LABEL_OVERRIDES: Record<string, string> = {
  "Nueva oferta confirmada": "Nueva oferta aceptada",
};
export const ESTADOS_TODOS = [
  "Pendiente",
  "Aceptado",
  "Cancelado",
  "Recogida solicitada",
  "Recogida generada",
  "En tránsito",
  "Recibido",
  "Check in OK",
  "En revisión",
  "Oferta confirmada",
  "Pendiente factura",
  "Factura recibida",
  "Pendiente de pago",
  "Pagado",
  "Nueva oferta",
  "Nueva oferta enviada",
  "Nueva oferta confirmada",
  "Rechazada",
  "Devolución iniciada",
  "Equipo enviado",
  "Recibido por el cliente",
  "Nuevo contrato",
  "Contrato firmado",
]
export const ESTADOS_PIPELINEADMIN = [
  "Pendiente",
  "Aceptado",
  "Cancelado",
  "Recogida solicitada",
  "Recogida generada",
  "En tránsito",
  "Recibido",
  "Check in OK",
  "En revisión",
  "Oferta confirmada",
  "Pendiente factura",
  "Nueva oferta enviada",
  "Nueva oferta",
  "Nueva oferta confirmada",
  "Rechazada",
  "Devolución iniciada",
  "Equipo enviado",
  "Recibido por el cliente",
]
export const ESTADOS_OPERACIONESADMIN = [
  "Pendiente factura",
  "Factura recibida",
  "Pendiente de pago",
  "Pagado",
  "Recibido por el cliente",
  "Nuevo contrato",
  "Contrato firmado",
]
export const ESTADOS_OPERACIONEPARTNER = [
  "Factura recibida",
  "Pendiente de pago",
  "Pagado",
  "Nuevo contrato",
  "Contrato firmado",
]
