from .oportunidad import OportunidadViewSet, HistorialOportunidadViewSet
from .dispositivo import (
    DispositivoViewSet,
    DispositivoRealCreateAPIView,
    DispositivosRealesDeOportunidadView,
    DispositivosRealesDeOportunidadGlobalView,
    ConfirmarRecepcionGlobalView,
    borrar_dispositivo_real,
    crear_dispositivo_real_global,
    actualizar_dispositivo_real_global,
)
from .cliente import ClienteViewSet, ComentarioClienteViewSet
from .tienda import TiendaViewSet
from .legal import (
    B2CContratoViewSet,
    B2CContratoFlagsAPIView,
    B2CContratoKycFinalizarAPIView,
    B2CContratoRenovarKYCApiView,
    B2CContratoReenviarKYCApiView,
    B2CContratoPdfPublicAPIView,
    B2CContratoPdfPreviewByToken,
    condiciones_b2c_pdf,
    LegalTemplateView,
    LegalTemplatePublishView,
    LegalTemplateVersionsView,
    LegalRenderPreviewView,
)
from .user import UsuarioTenantViewSet, cambiar_contraseña, cambiar_contraseña_usuario
from .kpis import (
    ValorPorTiendaAPIView,
    mi_dashboard,
    kpi_comisiones_comercial,
    kpi_comisiones_store_manager,
    kpi_comisiones_manager,
    kpi_resumen_por_rol,
)
from .documento import SubirFacturaView, descargar_documento
from .objetivo import ObjetivoViewSet, ObjetivoResumenAPIView

__all__ = [
    "OportunidadViewSet",
    "HistorialOportunidadViewSet",
    "DispositivoViewSet",
    "dispositivos_global_oportunidad",
    "dispositivo_global_detalle",
    "DispositivoRealCreateAPIView",
    "DispositivosRealesDeOportunidadView",
    "DispositivosRealesDeOportunidadGlobalView",
    "ConfirmarRecepcionGlobalView",
    "borrar_dispositivo_real",
    "crear_dispositivo_real_global",
    "actualizar_dispositivo_real_global",
    "ClienteViewSet",
    "ComentarioClienteViewSet",
    "TiendaViewSet",
    "B2CContratoViewSet",
    "B2CContratoFlagsAPIView",
    "B2CContratoKycFinalizarAPIView",
    "B2CContratoRenovarKYCApiView",
    "B2CContratoReenviarKYCApiView",
    "B2CContratoPdfPublicAPIView",
    "B2CContratoPdfPreviewByToken",
    "condiciones_b2c_pdf",
    "LegalTemplateView",
    "LegalTemplatePublishView",
    "LegalTemplateVersionsView",
    "LegalRenderPreviewView",
    "UsuarioTenantViewSet",
    "cambiar_contraseña",
    "cambiar_contraseña_usuario",
    "ValorPorTiendaAPIView",
    "mi_dashboard",
    "kpi_comisiones_comercial",
    "kpi_comisiones_store_manager",
    "kpi_comisiones_manager",
    "kpi_resumen_por_rol",
    "SubirFacturaView",
    "descargar_documento",
    "ObjetivoViewSet",
    "ObjetivoResumenAPIView",
]
