# Generated by Django 5.2.4 on 2025-07-10 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón social')),
                ('cif', models.CharField(max_length=20, verbose_name='CIF')),
                ('contacto', models.CharField(max_length=100, verbose_name='Persona de contacto')),
                ('posicion', models.CharField(max_length=100, verbose_name='Posición')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioOportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('respondida', 'Respondida')], default='pendiente', max_length=20)),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('iPhone', 'iPhone'), ('MacBook', 'MacBook'), ('iMac', 'iMac'), ('iPad', 'iPad'), ('Otro', 'Otro')], max_length=20)),
                ('año', models.IntegerField(blank=True, null=True)),
                ('imei', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_fisico', models.CharField(blank=True, choices=[('perfecto', 'Perfecto'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('dañado', 'Dañado')], max_length=20, null=True)),
                ('estado_funcional', models.CharField(blank=True, choices=[('funciona', 'Funciona correctamente'), ('no_enciende', 'No enciende'), ('pantalla_rota', 'Pantalla rota'), ('error_hardware', 'Error de hardware')], max_length=30, null=True)),
                ('comentarios_cliente', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado_valoracion', models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('muy_bueno', 'Muy bueno'), ('bueno', 'Bueno'), ('a_revision', 'A revisión')], max_length=20, null=True)),
                ('precio_orientativo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_valoracion', models.DateTimeField(blank=True, null=True)),
                ('fecha_caducidad', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('detalle', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='NotaInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('auditado', 'Auditado'), ('valorado', 'Valorado'), ('cerrado', 'Cerrado')], default='pendiente', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'checkouters_oportunidad',
            },
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_problema', models.TextField()),
                ('partes_necesarias', models.TextField(blank=True, null=True)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comentarios_tecnico', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('valorado', 'Valorado'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_valoracion', models.DateTimeField(blank=True, null=True)),
                ('fecha_respuesta_cliente', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
