# Generated by Django 5.2.4 on 2025-07-10 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
