# Generated by Django 5.2.4 on 2025-07-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0003_dispositivo_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidad',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('cancelado', 'Cancelado'), ('en_transito', 'En tránsito'), ('recibido', 'Recibido'), ('oferta_final', 'Oferta final'), ('aceptado', 'Aceptado'), ('factura_recibida', 'Factura recibida'), ('pagado', 'Pagado')], default='pendiente', max_length=50),
        ),
    ]
