# Generated by Django 5.2.4 on 2025-07-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0004_alter_oportunidad_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
            ],
        ),
    ]
