# Generated by Django 5.2.4 on 2025-07-11 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0005_tienda'),
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidad',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkouters.tienda'),
        ),
        migrations.CreateModel(
            name='UserTenantExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_manager', models.BooleanField(default=False)),
                ('tienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkouters.tienda')),
                ('user_permissions', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='permissions.usertenantpermissions')),
            ],
        ),
    ]
