# Generated by Django 5.2.4 on 2025-07-11 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0006_oportunidad_tienda_usertenantextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkouters.tienda'),
        ),
    ]
