# Generated by Django 5.2.4 on 2025-07-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0007_cliente_tienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidad',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Cancelado', 'Cancelado'), ('Recogida generada', 'Recogida generada'), ('En tránsito', 'En tránsito'), ('Recibido', 'Recibido'), ('En revisión', 'En revisión'), ('Oferta confirmada', 'Oferta confirmada'), ('Pendiente factura', 'Pendiente factura'), ('Factura recibida', 'Factura recibida'), ('Pendiente de pago', 'Pendiente de pago'), ('Pagado', 'Pagado'), ('Nueva oferta enviada', 'Nueva oferta enviada'), ('Rechazada', 'Rechazada'), ('Devolución iniciada', 'Devolución iniciada'), ('Equipo enviado', 'Equipo enviado'), ('Recibido por el cliente', 'Recibido por el cliente')], default='pendiente', max_length=50),
        ),
    ]
