# Generated by Django 5.2.4 on 2025-07-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0009_alter_oportunidad_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='tipo',
            field=models.CharField(choices=[('iPhone', 'iPhone'), ('MacBook', 'MacBook'), ('iMac', 'iMac'), ('iPad', 'iPad'), ('Mac Pro', 'Mac Pro'), ('Otro', 'Otro')], max_length=20),
        ),
    ]
