# Generated by Django 5.2.4 on 2025-07-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0011_historialoportunidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='tipo',
            field=models.CharField(choices=[('iPhone', 'iPhone'), ('MacBook Air', 'MacBook Air'), ('MacBook Pro', 'MacBook Pro'), ('iMac', 'iMac'), ('iPad', 'iPad'), ('Mac Pro', 'Mac Pro'), ('Mac Studio', 'Mac Studio'), ('Mac mini', 'Mac mini'), ('Otro', 'Otro')], max_length=20),
        ),
    ]
