# Generated by Django 5.2.4 on 2025-07-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0012_alter_dispositivo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidad',
            name='direccion_recogida',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='horario_recogida',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='instrucciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='persona_contacto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
