# Generated by Django 5.2.4 on 2025-07-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0013_oportunidad_direccion_recogida_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oportunidad',
            old_name='direccion_recogida',
            new_name='calle',
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='piso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='poblacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='puerta',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
