# Generated by Django 5.2.4 on 2025-07-18 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0014_rename_direccion_recogida_oportunidad_calle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='oportunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='checkouters.oportunidad'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='checkouters.dispositivo'),
        ),
    ]
