# Generated by Django 5.2.4 on 2025-07-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0015_documento_oportunidad_alter_documento_dispositivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('factura', 'Factura'), ('otro', 'Otro')], default='factura', max_length=50),
        ),
    ]
