# Generated by Django 5.2.4 on 2025-07-21 08:13

import checkouters.storage
import checkouters.utils.documentos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0016_documento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='nombre_original',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(storage=checkouters.storage.PrivateDocumentStorage(), upload_to=checkouters.utils.documentos.ruta_documento),
        ),
    ]
