# Generated by Django 5.2.4 on 2025-07-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0017_documento_nombre_original_alter_documento_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidad',
            name='fecha_inicio_pago',
            field=models.DateTimeField(blank=True, help_text="Fecha en que se cambió a 'Pendiente de pago'", null=True),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='plazo_pago_dias',
            field=models.IntegerField(blank=True, help_text="Días máximo de pago tras cambiar a 'Pendiente de pago'", null=True),
        ),
    ]
