# Generated by Django 5.2.4 on 2025-07-21 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0018_oportunidad_fecha_inicio_pago_and_more'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField(blank=True, null=True)),
                ('imei', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_fisico', models.CharField(blank=True, choices=[('perfecto', 'Perfecto'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('dañado', 'Dañado')], max_length=20, null=True)),
                ('estado_funcional', models.CharField(blank=True, choices=[('funciona', 'Funciona correctamente'), ('no_enciende', 'No enciende'), ('pantalla_rota', 'Pantalla rota'), ('error_hardware', 'Error de hardware')], max_length=30, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('recibido', models.BooleanField(default=True)),
                ('auditado', models.BooleanField(default=False)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('capacidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos_reales', to='productos.capacidad')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_reales', to='productos.modelo')),
                ('oportunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_reales', to='checkouters.oportunidad')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivo_real', to='checkouters.dispositivo')),
            ],
        ),
    ]
