# Generated by Django 5.2.4 on 2025-07-23 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0020_alter_oportunidad_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='tienda',
            name='direccion_calle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tienda',
            name='direccion_cp',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='tienda',
            name='direccion_pais',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tienda',
            name='direccion_piso',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tienda',
            name='direccion_poblacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tienda',
            name='direccion_provincia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tienda',
            name='direccion_puerta',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tienda',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiendas_responsables', to=settings.AUTH_USER_MODEL),
        ),
    ]
