# Generated by Django 5.2.4 on 2025-07-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0022_dispositivo_uuid_dispositivoreal_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='uuid',
        ),
    ]
