# Generated by Django 5.2.4 on 2025-07-26 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0023_remove_dispositivo_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivoreal',
            name='uuid',
        ),
    ]
