# Generated by Django 5.2.4 on 2025-07-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0025_dispositivoreal_fecha_auditoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidad',
            name='numero_seguimiento',
            field=models.CharField(blank=True, help_text='Número de seguimiento del envío', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='url_seguimiento',
            field=models.URLField(blank=True, help_text='Enlace de seguimiento proporcionado por el transportista', max_length=300, null=True),
        ),
    ]
