# Generated by Django 5.2.4 on 2025-07-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0026_oportunidad_numero_seguimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidad',
            name='correo_recogida',
            field=models.EmailField(blank=True, help_text='Correo electrónico de contacto para la recogida', max_length=255, null=True),
        ),
    ]
