# Generated by Django 5.2.4 on 2025-07-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0027_oportunidad_correo_recogida'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='precio_orientativoexcelente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
