# Generated by Django 5.2.4 on 2025-07-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0028_dispositivo_precio_orientativoexcelente'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivoreal',
            name='precio_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
