# Generated by Django 5.2.4 on 2025-08-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0029_dispositivoreal_precio_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contacto_financiero',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo_financiero',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_calle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_cp',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_pais',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_piso',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_poblacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_provincia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_puerta',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_empleados',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_financiero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='vertical',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='vertical_secundaria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Cancelado', 'Cancelado'), ('Recogida solicitada', 'Recogida solicitada'), ('Recogida generada', 'Recogida generada'), ('En tránsito', 'En tránsito'), ('Recibido', 'Recibido'), ('Check in OK', 'Check in OK'), ('En revisión', 'En revisión'), ('Oferta confirmada', 'Oferta confirmada'), ('Pendiente factura', 'Pendiente factura'), ('Factura recibida', 'Factura recibida'), ('Pendiente de pago', 'Pendiente de pago'), ('Pagado', 'Pagado'), ('Nueva oferta enviada', 'Nueva oferta enviada'), ('Rechazada', 'Rechazada'), ('Devolución iniciada', 'Devolución iniciada'), ('Equipo enviado', 'Equipo enviado'), ('Recibido por el cliente', 'Recibido por el cliente'), ('Nueva oferta enviada', 'Nueva oferta enviada'), ('Nueva oferta confirmada', 'Nueva oferta confirmada'), ('Nuevo contrato', 'Nuevo contrato'), ('Contrato', 'Contrato')], default='Pendiente', max_length=50),
        ),
    ]
