# Generated by Django 5.2.4 on 2025-08-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0030_cliente_contacto_financiero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='aceptaciones',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dni_nie',
            field=models.CharField(blank=True, max_length=20, verbose_name='DNI/NIE'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nif',
            field=models.CharField(blank=True, max_length=20, verbose_name='NIF'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre comercial'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('empresa', 'Empresa'), ('autonomo', 'Autónomo'), ('particular', 'Particular')], default='empresa', help_text='Empresa / Autónomo / Particular', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cif',
            field=models.CharField(blank=True, max_length=20, verbose_name='CIF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contacto',
            field=models.CharField(blank=True, max_length=100, verbose_name='Persona de contacto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='posicion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(blank=True, max_length=255, verbose_name='Razón social'),
        ),
    ]
