# Generated by Django 5.2.4 on 2025-08-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0031_cliente_aceptaciones_cliente_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidad',
            name='canal',
            field=models.CharField(choices=[('b2b', 'B2B'), ('b2c', 'B2C')], db_index=True, default='b2b', help_text='Canal de la oportunidad (B2B/B2C).', max_length=4),
        ),
    ]
