# Generated by Django 5.2.4 on 2025-08-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0032_oportunidad_canal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oportunidad',
            name='canal',
        ),
        migrations.AddField(
            model_name='cliente',
            name='canal',
            field=models.CharField(choices=[('b2b', 'B2B'), ('b2c', 'B2C')], db_index=True, default='b2b', help_text='Canal del cliente (B2B/B2C).', max_length=4),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('canal', 'b2c'), ('tipo_cliente', 'particular')), models.Q(('canal', 'b2b'), ('tipo_cliente__in', ['empresa', 'autonomo'])), _connector='OR'), name='cliente_canal_consistente'),
        ),
    ]
