# Generated by Django 5.2.4 on 2025-08-12 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0033_remove_oportunidad_canal_cliente_canal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2CContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oportunidad_id', models.UUIDField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=32)),
                ('dni', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^[0-9XYZxyz][0-9]{7}[A-Za-z]$|^[A-Za-z0-9\\-\\.]{5,}$', 'DNI/NIE no válido')])),
                ('contrato_datos', models.JSONField(blank=True, default=dict)),
                ('otp_hash', models.CharField(blank=True, max_length=128)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('otp_intentos', models.PositiveSmallIntegerField(default=0)),
                ('otp_max_intentos', models.PositiveSmallIntegerField(default=5)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('otp_enviado', 'OTP enviado'), ('firmado', 'Firmado'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=16)),
                ('ultimo_envio_otp', models.DateTimeField(blank=True, null=True)),
                ('firmado_en', models.DateTimeField(blank=True, null=True)),
                ('firmado_por', models.CharField(blank=True, max_length=255)),
                ('ip_firmante', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('pdf', models.FileField(blank=True, upload_to='contratos/')),
                ('pdf_sha256', models.CharField(blank=True, max_length=64)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
