# Generated by Django 5.2.4 on 2025-08-12 18:00

import checkouters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0034_b2ccontrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2ccontrato',
            name='dni_anverso',
            field=models.ImageField(blank=True, null=True, upload_to=checkouters.models.utils.upload_path_anverso),
        ),
        migrations.AddField(
            model_name='b2ccontrato',
            name='dni_reverso',
            field=models.ImageField(blank=True, null=True, upload_to=checkouters.models.utils.upload_path_reverso),
        ),
        migrations.AddField(
            model_name='b2ccontrato',
            name='kyc_requerido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='b2ccontrato',
            name='kyc_retenido_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
