# Generated by Django 5.2.4 on 2025-08-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0035_b2ccontrato_dni_anverso_b2ccontrato_dni_reverso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b2ccontrato',
            name='kyc_requerido',
        ),
        migrations.RemoveField(
            model_name='b2ccontrato',
            name='kyc_retenido_hasta',
        ),
        migrations.AddField(
            model_name='b2ccontrato',
            name='kyc_completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='b2ccontrato',
            name='kyc_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='b2ccontrato',
            name='kyc_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='b2ccontrato',
            name='kyc_revocado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='b2ccontrato',
            name='kyc_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='b2ccontrato',
            name='tiene_dni_anverso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='b2ccontrato',
            name='tiene_dni_reverso',
            field=models.BooleanField(default=False),
        ),
    ]
