# Generated by Django 5.2.4 on 2025-08-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0036_remove_b2ccontrato_kyc_requerido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2ccontrato',
            name='kyc_retenido_hasta',
            field=models.DateTimeField(blank=True, help_text='Fecha hasta la que se retiene la documentación KYC.', null=True),
        ),
    ]
