# Generated by Django 5.2.4 on 2025-08-13 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0037_b2ccontrato_kyc_retenido_hasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2ccontrato',
            name='principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anexos', to='checkouters.b2ccontrato'),
        ),
        migrations.AddField(
            model_name='b2ccontrato',
            name='tipo',
            field=models.CharField(choices=[('marco', 'Contrato marco'), ('acta', 'Acta de recepción')], default='marco', max_length=10),
        ),
    ]
