# Generated by Django 5.2.4 on 2025-08-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0038_b2ccontrato_principal_b2ccontrato_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2ccontrato',
            name='pdf_generado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='b2ccontrato',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
