# Generated by Django 5.2.4 on 2025-08-14 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0039_b2ccontrato_pdf_generado_en_b2ccontrato_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='b2ccontrato',
            name='kyc_estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('docs_recibidos', 'Docs recibidos'), ('verificado', 'Verificado'), ('mismatch', 'No coincide'), ('rechazado', 'Rechazado')], db_index=True, default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='b2ccontrato',
            name='kyc_motivo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='b2ccontrato',
            name='kyc_verificado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='b2ccontrato',
            name='kyc_verificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_verificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='b2ccontrato',
            name='pago_bloqueado_por_kyc',
            field=models.BooleanField(default=True),
        ),
    ]
