# Generated by Django 5.2.4 on 2025-08-15 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0040_b2ccontrato_kyc_estado_b2ccontrato_kyc_motivo_and_more'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivoreal',
            name='imei',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddConstraint(
            model_name='dispositivo',
            constraint=models.UniqueConstraint(condition=models.Q(('imei__isnull', False), models.Q(('imei', ''), _negated=True)), fields=('oportunidad', 'imei'), name='uniq_imei_por_oportunidad_plan'),
        ),
        migrations.AddConstraint(
            model_name='dispositivoreal',
            constraint=models.UniqueConstraint(condition=models.Q(('imei__isnull', False), models.Q(('imei', ''), _negated=True)), fields=('oportunidad', 'imei'), name='uniq_imei_por_oportunidad_real'),
        ),
    ]
