# Generated by Django 5.2.4 on 2025-08-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0041_alter_dispositivoreal_imei_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('version', models.CharField(default='v1', max_length=20)),
                ('content', models.TextField(help_text='Markdown/HTML simple con {{ variables }}')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('slug', 'is_active')},
            },
        ),
    ]
