# Generated by Django 5.2.4 on 2025-08-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0042_legaltemplate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='legaltemplate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='legaltemplate',
            name='namespace',
            field=models.SlugField(default='default', help_text='p.ej. "default" o "tenant:<uuid>"'),
        ),
        migrations.AlterUniqueTogether(
            name='legaltemplate',
            unique_together={('namespace', 'slug', 'is_active')},
        ),
    ]
