# Generated by Django 5.2.4 on 2025-08-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0043_alter_legaltemplate_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='imei',
            field=models.CharField(blank=True, db_index=True, help_text='IMEI declarado por el cliente.', max_length=15, null=True),
        ),
    ]
