# Generated by Django 5.2.4 on 2025-08-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0044_alter_dispositivo_imei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidad',
            name='piso',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='puerta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
