# Generated by Django 5.2.4 on 2025-08-27 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0045_alter_oportunidad_piso_alter_oportunidad_puerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='ciclos_bateria',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='estado_espalda',
            field=models.CharField(blank=True, choices=[('sin_signos', 'Sin signos'), ('minimos', 'Mínimos'), ('algunos', 'Algunos'), ('desgaste_visible', 'Desgaste visible'), ('agrietado_roto', 'Agrietado/roto')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='estado_lados',
            field=models.CharField(blank=True, choices=[('sin_signos', 'Sin signos'), ('minimos', 'Mínimos'), ('algunos', 'Algunos'), ('desgaste_visible', 'Desgaste visible'), ('agrietado_roto', 'Agrietado/roto')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='estado_pantalla',
            field=models.CharField(blank=True, choices=[('sin_signos', 'Sin signos'), ('minimos', 'Mínimos'), ('algunos', 'Algunos'), ('desgaste_visible', 'Desgaste visible'), ('agrietado_roto', 'Agrietado/roto')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='funcionalidad_basica',
            field=models.CharField(blank=True, choices=[('ok', 'Todo funciona'), ('parcial', 'No totalmente funcional')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='pantalla_funcional_lineas_quemaduras',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='pantalla_funcional_pixeles_muertos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='pantalla_funcional_puntos_bril',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='salud_bateria_pct',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Cancelado', 'Cancelado'), ('Recogida solicitada', 'Recogida solicitada'), ('Recogida generada', 'Recogida generada'), ('En tránsito', 'En tránsito'), ('Recibido', 'Recibido'), ('Check in OK', 'Check in OK'), ('En revisión', 'En revisión'), ('Oferta confirmada', 'Oferta confirmada'), ('Pendiente factura', 'Pendiente factura'), ('Factura recibida', 'Factura recibida'), ('Pendiente de pago', 'Pendiente de pago'), ('Pagado', 'Pagado'), ('Nueva oferta enviada', 'Nueva oferta enviada'), ('Rechazada', 'Rechazada'), ('Devolución iniciada', 'Devolución iniciada'), ('Equipo enviado', 'Equipo enviado'), ('Recibido por el cliente', 'Recibido por el cliente'), ('Nueva oferta enviada', 'Nueva oferta enviada'), ('Nueva oferta confirmada', 'Nueva oferta confirmada'), ('Nuevo contrato', 'Nuevo contrato'), ('Contrato firmado', 'Contrato firmado')], default='Pendiente', max_length=50),
        ),
    ]
