# Generated by Django 5.2.4 on 2025-10-19 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0048_objetivo'),
        ('productos', '0028_add_mapping_metadata_to_staging'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivoreal',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos_reales', to='productos.modelo'),
        ),
        migrations.CreateModel(
            name='DispositivoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(help_text='Marca del dispositivo (Samsung, Xiaomi, Dell, LG, etc.)', max_length=100)),
                ('modelo', models.CharField(help_text='Modelo específico del dispositivo', max_length=255)),
                ('capacidad', models.CharField(blank=True, help_text='Ej: 256GB, 1TB SSD, configuración especial', max_length=100)),
                ('tipo', models.CharField(choices=[('movil', 'Móvil'), ('portatil', 'Portátil'), ('monitor', 'Monitor'), ('tablet', 'Tablet'), ('otro', 'Otro')], default='otro', help_text='Tipo de dispositivo', max_length=20)),
                ('precio_base_b2b', models.DecimalField(decimal_places=2, help_text='Precio base para canal B2B', max_digits=10)),
                ('precio_base_b2c', models.DecimalField(decimal_places=2, help_text='Precio base para canal B2C', max_digits=10)),
                ('ajuste_excelente', models.IntegerField(default=100, help_text='% del precio base para estado excelente (0-100)')),
                ('ajuste_bueno', models.IntegerField(default=80, help_text='% del precio base para estado bueno (0-100)')),
                ('ajuste_malo', models.IntegerField(default=50, help_text='% del precio base para estado malo (0-100)')),
                ('caracteristicas', models.JSONField(blank=True, default=dict, help_text='RAM, procesador, tamaño pantalla, etc. en formato JSON')),
                ('notas', models.TextField(blank=True, help_text='Descripción adicional o detalles específicos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, help_text='Soft delete: False para desactivar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos_personalizados_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispositivo Personalizado',
                'verbose_name_plural': 'Dispositivos Personalizados',
                'db_table': 'dispositivos_personalizados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dispositivoreal',
            name='dispositivo_personalizado',
            field=models.ForeignKey(blank=True, help_text='Dispositivo personalizado (Samsung, Xiaomi, Dell, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos_reales', to='checkouters.dispositivopersonalizado'),
        ),
        migrations.AddIndex(
            model_name='dispositivopersonalizado',
            index=models.Index(fields=['marca', 'modelo'], name='dispositivo_marca_f05dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='dispositivopersonalizado',
            index=models.Index(fields=['tipo'], name='dispositivo_tipo_a27dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='dispositivopersonalizado',
            index=models.Index(fields=['activo'], name='dispositivo_activo_97330f_idx'),
        ),
    ]
