# Generated by Django 5.2.4 on 2025-10-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0051_add_dispositivo_personalizado_to_dispositivo'),
    ]

    operations = [
    ]
