# Generated by Django 5.2.4 on 2025-10-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0052_dispositivo_es_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si la tienda está activa'),
        ),
    ]
