# Generated by Django 5.2.4 on 2025-10-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouters', '0053_tienda_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='es_manual',
            field=models.BooleanField(default=False),
        ),
    ]
