# Generated by Django 5.2.4 on 2025-10-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='ultimo_mensaje_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
